[package]

name = "rust-hl-lua-modules"
version = "0.1.0"
authors = [ "pierre.krieger1708@gmail.com" ]

[lib]
name = "rust_hl_lua_modules"
crate_type = ["dylib"]
plugin = true

[dependencies.hlua]
path = "../hlua"
