[package]

name = "modules-test"
version = "0.1.0"
authors = [ "pierre.krieger1708@gmail.com" ]

[lib]
name = "mylib"
crate_type = ["dylib"]
path = "module_test.rs"

[dependencies.rust-hl-lua-modules]
path = ".."
